// <auto-generated />
using System;
using BodyJournalAPI.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BodyJournalApi.Migrations
{
    [DbContext(typeof(BodyJournalContext))]
    partial class BodyJournalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BodyJournalAPI.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lunge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Leg extension"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Leg curl"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Standing calf raise"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Seated calf raise"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hip adductor"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bench press"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chest fly"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Push-up"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pull-down"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bent-over row"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Upright row"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Shoulder press"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Shoulder fly"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Lateral raise"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Shoulder shrug"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Pushdown"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Triceps extension"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Biceps curl"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Russian twist"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Leg raise"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Back extension"
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.ExerciseMuscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleId");

                    b.ToTable("ExerciseMuscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            MuscleId = 1,
                            Primary = false
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            MuscleId = 1,
                            Primary = false
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 4,
                            MuscleId = 1,
                            Primary = false
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 6,
                            MuscleId = 1,
                            Primary = false
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 7,
                            MuscleId = 1,
                            Primary = true
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 8,
                            MuscleId = 1,
                            Primary = true
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 1,
                            MuscleId = 2,
                            Primary = true
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 2,
                            MuscleId = 2,
                            Primary = true
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 3,
                            MuscleId = 2,
                            Primary = true
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 4,
                            MuscleId = 2,
                            Primary = true
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 5,
                            MuscleId = 2,
                            Primary = true
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 1,
                            MuscleId = 3,
                            Primary = false
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 2,
                            MuscleId = 3,
                            Primary = false
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 3,
                            MuscleId = 3,
                            Primary = true
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 4,
                            MuscleId = 3,
                            Primary = true
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 6,
                            MuscleId = 3,
                            Primary = true
                        },
                        new
                        {
                            Id = 17,
                            ExerciseId = 27,
                            MuscleId = 3,
                            Primary = true
                        },
                        new
                        {
                            Id = 18,
                            ExerciseId = 1,
                            MuscleId = 4,
                            Primary = true
                        },
                        new
                        {
                            Id = 19,
                            ExerciseId = 2,
                            MuscleId = 4,
                            Primary = true
                        },
                        new
                        {
                            Id = 20,
                            ExerciseId = 3,
                            MuscleId = 4,
                            Primary = true
                        },
                        new
                        {
                            Id = 21,
                            ExerciseId = 4,
                            MuscleId = 4,
                            Primary = true
                        },
                        new
                        {
                            Id = 22,
                            ExerciseId = 27,
                            MuscleId = 4,
                            Primary = true
                        },
                        new
                        {
                            Id = 23,
                            ExerciseId = 1,
                            MuscleId = 5,
                            Primary = true
                        },
                        new
                        {
                            Id = 24,
                            ExerciseId = 3,
                            MuscleId = 5,
                            Primary = true
                        },
                        new
                        {
                            Id = 25,
                            ExerciseId = 4,
                            MuscleId = 5,
                            Primary = true
                        },
                        new
                        {
                            Id = 26,
                            ExerciseId = 9,
                            MuscleId = 5,
                            Primary = true
                        },
                        new
                        {
                            Id = 27,
                            ExerciseId = 26,
                            MuscleId = 5,
                            Primary = true
                        },
                        new
                        {
                            Id = 28,
                            ExerciseId = 1,
                            MuscleId = 6,
                            Primary = false
                        },
                        new
                        {
                            Id = 29,
                            ExerciseId = 4,
                            MuscleId = 6,
                            Primary = true
                        },
                        new
                        {
                            Id = 30,
                            ExerciseId = 27,
                            MuscleId = 6,
                            Primary = true
                        },
                        new
                        {
                            Id = 31,
                            ExerciseId = 13,
                            MuscleId = 7,
                            Primary = true
                        },
                        new
                        {
                            Id = 32,
                            ExerciseId = 14,
                            MuscleId = 7,
                            Primary = true
                        },
                        new
                        {
                            Id = 33,
                            ExerciseId = 15,
                            MuscleId = 7,
                            Primary = true
                        },
                        new
                        {
                            Id = 34,
                            ExerciseId = 4,
                            MuscleId = 8,
                            Primary = false
                        },
                        new
                        {
                            Id = 35,
                            ExerciseId = 14,
                            MuscleId = 8,
                            Primary = false
                        },
                        new
                        {
                            Id = 36,
                            ExerciseId = 15,
                            MuscleId = 8,
                            Primary = false
                        },
                        new
                        {
                            Id = 37,
                            ExerciseId = 16,
                            MuscleId = 8,
                            Primary = true
                        },
                        new
                        {
                            Id = 38,
                            ExerciseId = 17,
                            MuscleId = 8,
                            Primary = false
                        },
                        new
                        {
                            Id = 39,
                            ExerciseId = 18,
                            MuscleId = 8,
                            Primary = false
                        },
                        new
                        {
                            Id = 40,
                            ExerciseId = 19,
                            MuscleId = 8,
                            Primary = false
                        },
                        new
                        {
                            Id = 41,
                            ExerciseId = 20,
                            MuscleId = 8,
                            Primary = true
                        },
                        new
                        {
                            Id = 42,
                            ExerciseId = 1,
                            MuscleId = 9,
                            Primary = true
                        },
                        new
                        {
                            Id = 43,
                            ExerciseId = 4,
                            MuscleId = 9,
                            Primary = false
                        },
                        new
                        {
                            Id = 44,
                            ExerciseId = 12,
                            MuscleId = 9,
                            Primary = false
                        },
                        new
                        {
                            Id = 45,
                            ExerciseId = 24,
                            MuscleId = 9,
                            Primary = true
                        },
                        new
                        {
                            Id = 46,
                            ExerciseId = 25,
                            MuscleId = 9,
                            Primary = true
                        },
                        new
                        {
                            Id = 47,
                            ExerciseId = 26,
                            MuscleId = 9,
                            Primary = false
                        },
                        new
                        {
                            Id = 48,
                            ExerciseId = 10,
                            MuscleId = 10,
                            Primary = true
                        },
                        new
                        {
                            Id = 49,
                            ExerciseId = 11,
                            MuscleId = 10,
                            Primary = true
                        },
                        new
                        {
                            Id = 50,
                            ExerciseId = 12,
                            MuscleId = 10,
                            Primary = true
                        },
                        new
                        {
                            Id = 51,
                            ExerciseId = 13,
                            MuscleId = 10,
                            Primary = false
                        },
                        new
                        {
                            Id = 52,
                            ExerciseId = 14,
                            MuscleId = 10,
                            Primary = false
                        },
                        new
                        {
                            Id = 53,
                            ExerciseId = 10,
                            MuscleId = 11,
                            Primary = false
                        },
                        new
                        {
                            Id = 54,
                            ExerciseId = 11,
                            MuscleId = 11,
                            Primary = false
                        },
                        new
                        {
                            Id = 55,
                            ExerciseId = 12,
                            MuscleId = 11,
                            Primary = false
                        },
                        new
                        {
                            Id = 56,
                            ExerciseId = 13,
                            MuscleId = 11,
                            Primary = false
                        },
                        new
                        {
                            Id = 57,
                            ExerciseId = 14,
                            MuscleId = 11,
                            Primary = false
                        },
                        new
                        {
                            Id = 58,
                            ExerciseId = 16,
                            MuscleId = 11,
                            Primary = true
                        },
                        new
                        {
                            Id = 59,
                            ExerciseId = 17,
                            MuscleId = 11,
                            Primary = true
                        },
                        new
                        {
                            Id = 60,
                            ExerciseId = 18,
                            MuscleId = 11,
                            Primary = true
                        },
                        new
                        {
                            Id = 61,
                            ExerciseId = 19,
                            MuscleId = 11,
                            Primary = true
                        },
                        new
                        {
                            Id = 62,
                            ExerciseId = 20,
                            MuscleId = 11,
                            Primary = false
                        },
                        new
                        {
                            Id = 64,
                            ExerciseId = 10,
                            MuscleId = 12,
                            Primary = true
                        },
                        new
                        {
                            Id = 65,
                            ExerciseId = 12,
                            MuscleId = 12,
                            Primary = true
                        },
                        new
                        {
                            Id = 66,
                            ExerciseId = 17,
                            MuscleId = 12,
                            Primary = false
                        },
                        new
                        {
                            Id = 67,
                            ExerciseId = 21,
                            MuscleId = 12,
                            Primary = true
                        },
                        new
                        {
                            Id = 68,
                            ExerciseId = 22,
                            MuscleId = 12,
                            Primary = true
                        },
                        new
                        {
                            Id = 69,
                            ExerciseId = 13,
                            MuscleId = 13,
                            Primary = false
                        },
                        new
                        {
                            Id = 70,
                            ExerciseId = 14,
                            MuscleId = 13,
                            Primary = false
                        },
                        new
                        {
                            Id = 71,
                            ExerciseId = 15,
                            MuscleId = 13,
                            Primary = false
                        },
                        new
                        {
                            Id = 72,
                            ExerciseId = 16,
                            MuscleId = 13,
                            Primary = false
                        },
                        new
                        {
                            Id = 73,
                            ExerciseId = 23,
                            MuscleId = 13,
                            Primary = true
                        },
                        new
                        {
                            Id = 74,
                            ExerciseId = 4,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 75,
                            ExerciseId = 13,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 76,
                            ExerciseId = 14,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 77,
                            ExerciseId = 15,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 78,
                            ExerciseId = 16,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 79,
                            ExerciseId = 18,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 80,
                            ExerciseId = 20,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 81,
                            ExerciseId = 22,
                            MuscleId = 14,
                            Primary = false
                        },
                        new
                        {
                            Id = 82,
                            ExerciseId = 23,
                            MuscleId = 14,
                            Primary = false
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.ExerciseWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseWorkouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            WorkoutId = 1
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Muscle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quadriceps"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gluteus"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hips"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lower back"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Trapezius"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Abdominals"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pectorals"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Deltoids"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 10,
                            Reps = 8,
                            Sets = 3,
                            Time = "07/20/2020 14:10",
                            UserId = 1,
                            Weight = 200
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 1,
                            Reps = 5,
                            Sets = 3,
                            Time = "07/20/2020 14:10",
                            UserId = 0,
                            Weight = 300
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 14,
                            Reps = 20,
                            Sets = 1,
                            Time = "07/20/2020 14:10",
                            UserId = 0,
                            Weight = 0
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 17,
                            Reps = 8,
                            Sets = 3,
                            Time = "07/20/2020 14:10",
                            UserId = 0,
                            Weight = 150
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.Recovery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Fatigue")
                        .HasColumnType("int");

                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recovery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fatigue = 1,
                            MuscleId = 1,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Fatigue = 1,
                            MuscleId = 2,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Fatigue = 1,
                            MuscleId = 3,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Fatigue = 1,
                            MuscleId = 4,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Fatigue = 1,
                            MuscleId = 5,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Fatigue = 1,
                            MuscleId = 6,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Fatigue = 1,
                            MuscleId = 7,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Fatigue = 1,
                            MuscleId = 8,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Fatigue = 1,
                            MuscleId = 9,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Fatigue = 1,
                            MuscleId = 10,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Fatigue = 1,
                            MuscleId = 11,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Fatigue = 1,
                            MuscleId = 12,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Fatigue = 1,
                            MuscleId = 13,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Fatigue = 1,
                            MuscleId = 14,
                            Time = "07/20/2020 14:10",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutStart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rating = (byte)5,
                            UserId = 1,
                            WorkoutEnd = "07/20/2020 15:10",
                            WorkoutId = 1,
                            WorkoutStart = "07/20/2020 14:10"
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "a@gmail.com",
                            FirstName = "Andrew",
                            LastName = "Philpott",
                            PasswordHash = new byte[] { 72, 13, 104, 149, 133, 49, 53, 25, 157, 98, 72, 115, 151, 58, 150, 122, 82, 87, 135, 156, 56, 217, 193, 217, 82, 246, 90, 60, 12, 59, 170, 147, 46, 77, 147, 141, 155, 104, 81, 205, 4, 248, 155, 202, 164, 49, 98, 68, 116, 94, 225, 226, 85, 193, 111, 58, 48, 246, 190, 111, 130, 224, 203, 141 },
                            PasswordSalt = new byte[] { 150, 185, 20, 92, 26, 175, 214, 159, 175, 37, 207, 214, 253, 75, 134, 41, 119, 97, 234, 17, 240, 48, 93, 20, 119, 72, 192, 116, 190, 76, 5, 218, 125, 228, 32, 188, 61, 213, 75, 245, 46, 114, 42, 4, 29, 46, 79, 104, 143, 73, 192, 106, 116, 112, 194, 113, 137, 167, 212, 112, 9, 25, 111, 170, 241, 70, 64, 8, 63, 56, 120, 96, 223, 141, 191, 130, 23, 77, 197, 94, 179, 35, 16, 175, 11, 119, 254, 173, 55, 118, 234, 134, 83, 225, 161, 107, 2, 121, 31, 162, 69, 165, 36, 40, 185, 172, 31, 9, 150, 5, 98, 22, 159, 105, 231, 118, 231, 255, 88, 138, 252, 252, 3, 23, 250, 71, 83, 90 },
                            UserName = "Nxtstp"
                        },
                        new
                        {
                            Id = 2,
                            Email = "b@gmail.com",
                            FirstName = "b",
                            LastName = "b",
                            PasswordHash = new byte[] { 72, 13, 104, 149, 133, 49, 53, 25, 157, 98, 72, 115, 151, 58, 150, 122, 82, 87, 135, 156, 56, 217, 193, 217, 82, 246, 90, 60, 12, 59, 170, 147, 46, 77, 147, 141, 155, 104, 81, 205, 4, 248, 155, 202, 164, 49, 98, 68, 116, 94, 225, 226, 85, 193, 111, 58, 48, 246, 190, 111, 130, 224, 203, 141 },
                            PasswordSalt = new byte[] { 150, 185, 20, 92, 26, 175, 214, 159, 175, 37, 207, 214, 253, 75, 134, 41, 119, 97, 234, 17, 240, 48, 93, 20, 119, 72, 192, 116, 190, 76, 5, 218, 125, 228, 32, 188, 61, 213, 75, 245, 46, 114, 42, 4, 29, 46, 79, 104, 143, 73, 192, 106, 116, 112, 194, 113, 137, 167, 212, 112, 9, 25, 111, 170, 241, 70, 64, 8, 63, 56, 120, 96, 223, 141, 191, 130, 23, 77, 197, 94, 179, 35, 16, 175, 11, 119, 254, 173, 55, 118, 234, 134, 83, 225, 161, 107, 2, 121, 31, 162, 69, 165, 36, 40, 185, 172, 31, 9, 150, 5, 98, 22, 159, 105, 231, 118, 231, 255, 88, 138, 252, 252, 3, 23, 250, 71, 83, 90 },
                            UserName = "b"
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.UserExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 10,
                            Intensity = 4,
                            Name = "Bench Press",
                            Reps = 8,
                            Sets = 3,
                            UserId = 1,
                            Weight = 180
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 1,
                            Intensity = 4,
                            Name = "Squat",
                            Reps = 15,
                            Sets = 3,
                            UserId = 0,
                            Weight = 250
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Full Body",
                            Notes = "Rest 1 minute between sets",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.ExerciseMuscle", b =>
                {
                    b.HasOne("BodyJournalAPI.Entities.Exercise", "Exercise")
                        .WithMany("Muscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyJournalAPI.Entities.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.ExerciseWorkout", b =>
                {
                    b.HasOne("BodyJournalAPI.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodyJournalAPI.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BodyJournalAPI.Entities.Session", b =>
                {
                    b.HasOne("BodyJournalAPI.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
